import './globals.css'
import { Kalam } from 'next/font/google';

const kalam = Kalam({ 
  subsets: ['latin'],
  weight:["400", "300"],
  display:"swap"
});

export const metadata = {
  title: 'Langi Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kalam.className} bg-black text-slate-100 container mx-auto p-4`}>{children}</body>
    </html>
  )
}
